name: Update README all day at 09:00

on:
  push:
  workflow_dispatch:
  schedule:
    # “At 09:00 on every day-of-week from Monday through Friday.”
    - cron: '20 16 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Mandel-AG
          author_email: a.mandel06@gmail.com
          commit: --signoff
          message: 'chore: :memo: automatically README.md'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.MySecretGh }}
